import 'package:diego_yangua_movies/data/models/genre_enum.dart';
import 'package:json_annotation/json_annotation.dart';

part 'movie_model.g.dart';

/// Movie model for movies
/// [title], [description], [rating], [genre]
/// [id] is String because it is generated by the API
@JsonSerializable()
class Movie {
  final String? id;
  final String title;
  final String description;
  final double rating;
  final Genre genre;

  Movie({
    this.id,
    required this.title,
    required this.description,
    required this.rating,
    required this.genre,
  });

  factory Movie.fromJson(Map<String, dynamic> json) => _$MovieFromJson(json);

  Map<String, dynamic> toJson() => _$MovieToJson(this);

  @override
  String toString() {
    return 'Movie(id: $id, title: $title, description: $description, rating: $rating, genre: $genre)';
  }
}
